Repository ltb-project/service-desk, pull requests merged in 2023-05, with the labels that each got.

#94 Missing replacement for lang value (issue #92)
  htdocs/index.php
Labels: bug

#95 Some documentation improvements
  docs/audit.rst
  docs/config_mail.rst
Labels: documentation

#98 Add IP in audit
  docs/audit.rst
  lib/audit.inc.php
Labels: enhancement

#99 Provide result codes for lock/unlock account actions
  htdocs/lockaccount.php
  htdocs/unlockaccount.php
Labels: enhancement
